# supabase/config.toml
[project]
id = "your-project-ref" # Replace this with your actual Supabase project ref
name = "nuvon-dashboard"

[api]
port = 54321

[studio]
enabled = true
port = 54323

[db]
port = 54322